/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasPaneles;

import Listas.Clase;
import Listas.MostrarTabla;
import SplitID.SplitUtils;
import SplitID.SamuraiPaper;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.*;

/**
 *
 * @author javier
 */
public class SplitPanel extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    
    private MiModelo modeloTabla;
    private JTable tablaElem;
    
    private Set<String> lisIdsSplited = new HashSet<String>();
    
    
    public SplitPanel(java.awt.Frame parent, boolean modal,ArrayList<MostrarTabla> listId,ArrayList<Clase> lisClases) {
        super(parent, modal);
        initComponents();
        
        modeloTabla = new MiModelo();
        tablaElem = new JTable(modeloTabla);
        jScrollSplit.setViewportView(tablaElem);

        modeloTabla.addColumn("IDENTIFICADOR");
        modeloTabla.addColumn("DIVISIÓN GREEDY");
        modeloTabla.addColumn("DIVISIÓN SAMURAI");
        
        Object[] filaTabla = new Object[3];
        String nomIde;
        String splitIde;
        SamuraiPaper samurai;
        
        
        if(listId!=null){
            for(MostrarTabla ide: listId){
                nomIde = ide.getNomId();
                filaTabla[0]= nomIde;
                splitIde = SplitUtils.ejecutar(nomIde,true);//true=caso 1 de upperlower false=caso 2
                filaTabla[1]= splitIde.replaceAll(" ", "-");//para que se destaque la separación

                lisIdsSplited.add(filaTabla[1].toString().toLowerCase());
                
                samurai = new SamuraiPaper(lisClases.get(0),"strDomicilio");
                
                //samurai.mixedCaseSplit();
                
                //splitIde = Samurai.ejecutar(nomIde);
                //filaTabla[2]= splitIde.replaceAll(" ", "   ");//para que se destaque la separación
                modeloTabla.addRow(filaTabla);
            }
        }

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {

            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    public Set<String> getLisIdsSplited() {
        return lisIdsSplited;
    } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        jScrollSplit = new javax.swing.JScrollPane();

        setTitle("Técnicas de División");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        cancelButton.setText("Cerrar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 625, Short.MAX_VALUE)
                        .addComponent(cancelButton))
                    .addComponent(jScrollSplit))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-722)/2, (screenSize.height-547)/2, 722, 547);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane jScrollSplit;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}
