/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ExtractID;

import Listas.Clase;
import Listas.Comentario;
import Listas.ListaClase;
import Listas.MostrarTabla;
import VentanasPaneles.AcercaDe;
import VentanasPaneles.ClosableTabbedPane;
import VentanasPaneles.CodigoPanel;
import VentanasPaneles.SplitPanel;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.antlr.runtime.ANTLRFileStream;
import org.antlr.runtime.CommonTokenStream;
import org.antlr.runtime.RecognitionException;

/**
 *
 * @author javier
 */
public class Main extends javax.swing.JFrame {

    private static File[] archivosAnalisisId = null;
    
    private ClosableTabbedPane jTabbedEsp;


    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
                
        jTabbedEsp = new ClosableTabbedPane();
        
        jTabbedEsp.setFocusable(false);
        
        jTabbedEsp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedEsp, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedEsp, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        
        jTabbedEsp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedEspStateChanged(evt);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemCerrTodo = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemAlgGreedy = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Identifier Analyzer");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir Archivos...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItemCerrTodo.setText("Cerrar Todo");
        jMenuItemCerrTodo.setEnabled(false);
        jMenuItemCerrTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrTodoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCerrTodo);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Dividir Id");

        jMenuItemAlgGreedy.setText("Algoritmo Greedy...");
        jMenuItemAlgGreedy.setEnabled(false);
        jMenuItemAlgGreedy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlgGreedyActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAlgGreedy);

        jMenuItem5.setText("Algoritmo Samurai...");
        jMenuItem5.setEnabled(false);
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Expandir Id");
        jMenu3.setEnabled(false);
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");

        jMenuItem6.setText("Acerca de...");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(564, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-847)/2, (screenSize.height-517)/2, 847, 517);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        AcercaDe ad;
        ad = new AcercaDe(new javax.swing.JFrame(), true);

        ad.setVisible(true);

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        String canonicalPath = "";
        try {
            canonicalPath = new File(".").getCanonicalPath();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        File file = new File(canonicalPath);


        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(file);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("java", "java");
        fileChooser.setFileFilter(filter);

        fileChooser.setMultiSelectionEnabled(true);

        int seleccion = fileChooser.showOpenDialog(fileChooser);
        boolean noErrorSintactico = true;

        if (seleccion == JFileChooser.APPROVE_OPTION) {

            //jMenuItem1.setEnabled(false);
             jMenuItemCerrTodo.setEnabled(true);

            archivosAnalisisId = fileChooser.getSelectedFiles();

            try {
                ListaClase.clean();

                for (File fileAnalisis : archivosAnalisisId) {

                    JavaLexer lex = new JavaLexer(new ANTLRFileStream(fileAnalisis.getAbsolutePath()));
                    CommonTokenStream tokens = new CommonTokenStream(lex);
                    JavaParser g = new JavaParser(tokens);

                    Clase unaClase;
                    try {
                        g.compilationUnit();
                        noErrorSintactico = g.ocurrioError();

                        unaClase = g.getClaseAnalisis();
                        unaClase.setPunteroArchivo(fileAnalisis);//seteo puntero archivo en la clase 
                        /////comentarios/////
                        ArrayList<Comentario> lisCom = lex.getLisCom(); //comentarios del lexer 
                        unaClase.setLisComentario(lisCom);
                        unaClase.setearAmbienteCometario();//seteo ambientes de comentarios
                        unaClase.cargarIdTablaClase();//cargo elementos para las tablas
                        unaClase.setLisLiterales(g.getLisLiterales());
                        /////////////////////
                        ListaClase.addElemLisClases(unaClase);
                        

                    } catch (RecognitionException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
               

            } catch (IOException e) {
            }

            if (noErrorSintactico) {

                for (Clase claseAnalisis : ListaClase.getLisClases()) {

                    CodigoPanel codigoPanel = new CodigoPanel(claseAnalisis);
                //jTabbedPaneCodigo.add(claseAnalisis.getPunteroArchivo().getName(), codigoPanel);
                    jTabbedEsp.addTab(claseAnalisis.getPunteroArchivo().getName(), codigoPanel);
                }

                //jTabbedPaneAnalisis.add("Identificadores", new TablaBuscador(0));
                //jTabbedPaneAnalisis.add("Literales", new TablaBuscador(1));
                //jTabbedPaneAnalisis.add("Comentarios", new TablaBuscador(2));

                //jTabbedPaneCodigo.setVisible(true);
                jTabbedEsp.setVisible(true);
                jMenuItem3.setEnabled(true);
                //jMenuItem4.setEnabled(true);

            } else {
                JFrame p = new JFrame();
                JOptionPane.showMessageDialog(p, "Existen Errores Sintácticos en el(los) archivo(s) seleccionados, corríjalos y vuelva a intentarlo", "ERROR SINTÁCTICO", JOptionPane.ERROR_MESSAGE);
            }
        }   
        

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemCerrTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrTodoActionPerformed
        
        jTabbedEsp.removeAll();
        jMenuItemCerrTodo.setEnabled(false);
        jMenuItemAlgGreedy.setEnabled(false);
        
    }//GEN-LAST:event_jMenuItemCerrTodoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItemAlgGreedyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlgGreedyActionPerformed
        ArrayList<MostrarTabla> lisMt = new ArrayList<MostrarTabla>();
        for(Clase c: ListaClase.getLisClases()){
            lisMt.addAll(c.getIdTablaClase());
        }
        
        SplitPanel tb;
        tb = new SplitPanel(new javax.swing.JFrame(), true, lisMt);
        
        tb.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlgGreedyActionPerformed

    private void jTabbedEspStateChanged(javax.swing.event.ChangeEvent evt) {
        
        if(jTabbedEsp.getTabCount()==0){
            jMenuItemCerrTodo.setEnabled(false);
            jMenuItemAlgGreedy.setEnabled(false);
        }else{      
            jMenuItemCerrTodo.setEnabled(true);
            jMenuItemAlgGreedy.setEnabled(true);
        }
    }   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main principal = new Main();
                principal.setVisible(true);        
                
                principal.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemAlgGreedy;
    private javax.swing.JMenuItem jMenuItemCerrTodo;
    // End of variables declaration//GEN-END:variables
}
