package ExtractID;

import DictionaryDB.ConnectionDB;
import ExpandID.ExpandBasic;
import Listas.Archivo;
import Listas.Comentario;
import Listas.ListaArchivo;
import Listas.ProcesarXML;
import SplitID.Greedy;
import SplitID.Samurai;
import VentanasPaneles.AcercaDe;
import VentanasPaneles.ClosableTabbedPane;
import VentanasPaneles.CodigoPanel;
import VentanasPaneles.DiccionaryPanel;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.antlr.runtime.ANTLRStringStream;
import org.antlr.runtime.CommonTokenStream;
import org.jdesktop.swingx.util.OS;

/**
 *
 * @author Javier Azcurra
 */
public class Principal extends javax.swing.JFrame {

    private CodigoPanel codigoPanel;

    private static File[] archivosAnalisisId = null;

    private final ClosableTabbedPane jTabbedEsp;

    private JFileChooser fileChooser;
    private File currentDir;

    private static DiccionaryPanel dicPanel;

    public Principal() {

//        JFrame.setDefaultLookAndFeelDecorated(true);
//        SubstanceLookAndFeel.setCurrentTheme("org.jvnet.substance.theme.SubstanceCremeTheme");
//        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.ModerateSkin");
        initComponents();

        ListaArchivo.init();

        fileChooser = new JFileChooser();

        jTabbedEsp = new ClosableTabbedPane();

        jTabbedEsp.setFocusable(false);

        jTabbedEsp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        //jframe maximizado
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        jTabbedEsp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedEspStateChanged(evt);
            }
        });

    }

    private void jTabbedEspStateChanged(javax.swing.event.ChangeEvent evt) {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(layout);

        if (jTabbedEsp.getTabCount() == 0) {

            jMenuItemCerrTodo.setEnabled(false);
            jTabbedEsp.setVisible(false);
            jMenuRestBD.setEnabled(true);

            if (dicPanel != null) {
                dicPanel.removeAll();
                dicPanel = null;
            }

            //remueve el tab panne del desktop pane
            layout.removeLayoutComponent(jTabbedEsp);

        } else {//>0

            jTabbedEsp.setVisible(true);
            jMenuItemCerrTodo.setEnabled(true);
            jMenuRestBD.setEnabled(false);

            ///Agrega tab pane al desktoppane
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedEsp)
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedEsp)
            );
            ////            

        }

    }

    public static DiccionaryPanel getDicPanel() {

        if (dicPanel == null) {
            dicPanel = new DiccionaryPanel(new javax.swing.JFrame(), true);
        }

        return dicPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuAbrir = new javax.swing.JMenuItem();
        jMenuItemCerrTodo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        jMenuVerDic = new javax.swing.JMenuItem();
        jMenuRestBD = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Identifier Analyzer");

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        jMenuAbrir.setMnemonic('o');
        jMenuAbrir.setText("Abrir archivo(s) JAVA...");
        jMenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuAbrir);

        jMenuItemCerrTodo.setMnemonic('s');
        jMenuItemCerrTodo.setText("Cerrar Todo");
        jMenuItemCerrTodo.setEnabled(false);
        jMenuItemCerrTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrTodoActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItemCerrTodo);
        fileMenu.add(jSeparator1);

        jMenuItem3.setMnemonic('x');
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem3);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Diccionarios");

        jMenuVerDic.setMnemonic('t');
        jMenuVerDic.setText("Ver Diccionarios...");
        jMenuVerDic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVerDicActionPerformed(evt);
            }
        });
        editMenu.add(jMenuVerDic);

        jMenuRestBD.setMnemonic('y');
        jMenuRestBD.setText("Restablecer B.D.");
        jMenuRestBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRestBDActionPerformed(evt);
            }
        });
        editMenu.add(jMenuRestBD);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        jMenu4.setMnemonic('a');
        jMenu4.setText("Acerca de...");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenu4);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(410, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirActionPerformed

        currentDir = new File(System.getProperty("user.home"));

        fileChooser.setCurrentDirectory(currentDir);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("java", "JAVA");
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileFilter(filter);

        fileChooser.setMultiSelectionEnabled(true);

        int seleccion = fileChooser.showOpenDialog(fileChooser);
        boolean noErrorSintactico = true;

        if (seleccion == JFileChooser.APPROVE_OPTION) {

            archivosAnalisisId = fileChooser.getSelectedFiles();

            for (File fileAnalisis : archivosAnalisisId) {

                if (!fileAnalisis.exists()) {
                    JOptionPane.showMessageDialog(null, "Atención, el archivo: " + fileAnalisis.getName()
                            + " no existe", "Atención", JOptionPane.WARNING_MESSAGE);
                    continue;
                }

                if (ListaArchivo.containsFileName(fileAnalisis.getAbsolutePath())) {
                    JOptionPane.showMessageDialog(new JFrame(),
                            "El archivo con la ruta: " + "\"" + fileAnalisis.getAbsolutePath() + "\""
                            + "\nya se encuentra abierto!", "Atención", JOptionPane.WARNING_MESSAGE);
                    continue;
                }

                //jacobe para dar formato al codigo leido desde el archivo
                String prettyCode = prettyCode(fileAnalisis.getAbsolutePath());

                if (prettyCode.isEmpty()) {
                    JOptionPane.showMessageDialog(new JFrame(),
                            "El archivo con la ruta: " + "\"" + fileAnalisis.getAbsolutePath() + "\""
                            + "\nesta vacío o posee errores sintácticos,"
                            + "\nrevíselo e intente de nuevo.", "Atención", JOptionPane.WARNING_MESSAGE);
                    continue;
                }
                ///////////////

                JavaLexer lex = new JavaLexer(new ANTLRStringStream(prettyCode));
                CommonTokenStream tokens = new CommonTokenStream(lex);
                JavaParser g = new JavaParser(tokens);

                try {
                    g.compilationUnit();
                    noErrorSintactico = g.ocurrioError();

                } catch (Exception e) {

                    System.out.println(getStackTrace(e));
                    noErrorSintactico = false;
                }

                Archivo unArchivo = g.getArchivo();

                //control de carga de datos del parser
                if (!noErrorSintactico || unArchivo == null) {
                    JOptionPane.showMessageDialog(new JFrame(),
                            "Error fatal al analizar archivo: " + "\"" + fileAnalisis.getAbsolutePath() + "\"", "ERROR", JOptionPane.ERROR_MESSAGE);
                    continue;
                }

                ////////
                unArchivo.setFileName(fileAnalisis.getName());//nombre archivo java
                unArchivo.setFileNamePath(fileAnalisis.getAbsolutePath());//ruta del archivo java                
                unArchivo.setCode(prettyCode);//codigo leido de archivo

                /////comentarios/////
                ArrayList<Comentario> lisCom = lex.getLisCom(); //comentarios del lexer 
                unArchivo.setLisComentario(lisCom);

                ////Literales/////
                unArchivo.setLisLiterales(g.getLisLiterales());

                /////////////////////
                unArchivo.cargarInfoTabla();

                ListaArchivo.addElemLisArchivos(unArchivo);

                //Interfaz
                codigoPanel = new CodigoPanel(unArchivo);

                jTabbedEsp.addTab(unArchivo.getFileName(), fileAnalisis.getAbsolutePath(), codigoPanel);

            }
        }
    }//GEN-LAST:event_jMenuAbrirActionPerformed

    private void jMenuVerDicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVerDicActionPerformed
        getDicPanel().setVisible(true);
    }//GEN-LAST:event_jMenuVerDicActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

        AcercaDe a = new AcercaDe(new JFrame(), true);

        a.setVisible(true);

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItemCerrTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrTodoActionPerformed

        ListaArchivo.clear();
        jTabbedEsp.removeAll();
        jMenuItemCerrTodo.setEnabled(false);
        jMenuRestBD.setEnabled(true);

    }//GEN-LAST:event_jMenuItemCerrTodoActionPerformed

    private void jMenuRestBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRestBDActionPerformed

        if (dicPanel != null) {
            //para actualizar la ventana ante posibles cambios
            dicPanel.removeAll();
            dicPanel = null;
        }

        DictionaryDB.Dictionary.restartBd();
    }//GEN-LAST:event_jMenuRestBDActionPerformed

    public static String getStackTrace(final Throwable throwable) {
        final StringWriter sw = new StringWriter();
        final PrintWriter pw = new PrintWriter(sw, true);
        throwable.printStackTrace(pw);
        return sw.getBuffer().toString();
    }

    private String prettyCode(String path) {

        String output = "";

        try {

            BufferedReader reader = null;

            String dirJacobe = "";

            if (isLinux()) {
                dirJacobe = "jacobe/unix/jacobe";
            } else if (isWindows()) {
                dirJacobe = "jacobe/win/jacobe";
            } else {
                System.out.println("jacobe: No se reconoce el SO - Linux/Win");
                System.exit(0);
            }

            dirJacobe = LibPath.getLibPath() + dirJacobe;

            Runtime rt = Runtime.getRuntime();
            Process p;
            
            p = rt.exec(new String[]{dirJacobe, "-cfg=sun.cfg", path, "-stdout"});

            reader = new BufferedReader(new InputStreamReader(p.getInputStream()));

            //p.waitFor();

            String line = "";

            while ((line = reader.readLine()) != null) {
                output += line + "\n";
            }

        } catch (IOException ex) {
            System.out.println(getStackTrace(ex));
        }

        return output;

    }

    public static boolean isWindows() {

        return (OS.isWindows());
    }

    public static boolean isLinux() {

        return (OS.isLinux());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        LibPath p = new LibPath();

        p.setLibPath();

        String msgErr = "Ocurrió un error al procesar el archivo:\n\n";
        /* Create and display the form */
        switch (args.length) {

            case 1://si posee 1 arg se interpreta que es el xml

                String parent = new File(args[0]).getParent() == null ? "" : new File(args[0]).getParent() + "/";
                
                try {

                    Path path = Paths.get(args[0]);
                    
                    if(path.toString().toLowerCase().equals("checklib")){
                        System.out.println("Ruta de Librerias y programas: "+LibPath.getLibPath());
                        System.exit(0);                    
                    }

                    if (!path.toString().toLowerCase().endsWith(".xml")) {
                        System.out.println("El argumento debe ser un archivo xml: " + args[0]);
                        System.exit(0);
                    }

                    File f = new File(args[0]);
                    if (!f.exists()) {
                        System.out.println(msgErr + "El archivo: " + args[0] + " no existe");
                        System.exit(0);
                    }
                    
                    //se limpia archivo de salida xml
                    PrintWriter writer = new PrintWriter(new File(parent + "salida.xml"));
                    writer.print("");
                    writer.close();

                    ProcesarXML.leer(new File(args[0]));

                    Archivo archivo = new Archivo();

                    archivo.setLisComentario(ProcesarXML.getLisFrase());

                    archivo.setLisMostrarTabla(ProcesarXML.getLisMostrarTabla());
                    
//                    if(ProcesarXML.getClases().isEmpty()){
//                        System.out.println("El archivo xml debe tener especificado al menos una clase, revíselo e intente de nuevo");
//                        System.exit(0);
//                    }
                    
                    if(ProcesarXML.getLisIds().isEmpty()){
                        System.out.println("El archivo xml debe tener especificado al menos un identificador, revíselo e intente de nuevo");
                        System.exit(0);
                    }                    
                    
                    archivo.setLisClases(ProcesarXML.getClases());

                    //===================================
                    String arrayResult[];

                    ArrayList<String[]> lisResult = new ArrayList<>();

                    //procesar algoritmos
                    Greedy gre = new Greedy();

                    ConnectionDB.AbrirConBD();

                    ExpandBasic exp = new ExpandBasic(archivo);

                    Samurai sam = new Samurai(archivo);

                    String divResult[];

                    for (String id : ProcesarXML.getLisIds()) {

                        arrayResult = new String[5];

                        arrayResult[0] = id.trim();

                        arrayResult[1] = gre.ejecutar(arrayResult[0]).replaceAll(" ", "-");

                        arrayResult[2] = sam.ejecutar(arrayResult[0]).replaceAll(" ", "-");

                        divResult = arrayResult[1].split("-");

                        String append = "";

                        for (String s : divResult) {

                            append += exp.ejecutar(s, "", "") + " ";

                        }

                        arrayResult[3] = append.trim().isEmpty() ? "" : append.trim();

                        divResult = arrayResult[2].split("-");

                        append = "";

                        for (String s : divResult) {

                            append += exp.ejecutar(s, "", "") + " ";

                        }

                        arrayResult[4] = append.trim().isEmpty() ? "" : append.trim();

                        lisResult.add(arrayResult);
                    }

                    ConnectionDB.CerrarConBD();

                    //String parent = new File(args[0]).getParent() == null ?"":new File(args[0]).getParent()+"/";
                    ProcesarXML.escribir(lisResult, parent + "salida.xml");

                    System.out.println("El Archivo: " + args[0] + " se procesó con éxito");
                    System.out.println("El Archivo: " + parent + "salida.xml" + " se generó correctamente");

                } catch (Exception ex) {
                    System.out.println(msgErr + getStackTrace(ex));
                } finally {
                    System.exit(0);
                }

            case 0:// si no tiene args se interpreta analisis desde interfaz

                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new Principal().setVisible(true);
                    }
                });

                break;

            default:
                System.out.println("Cantidad de argumentos inválidos");

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenu4;
    private javax.swing.JMenuItem jMenuAbrir;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemCerrTodo;
    private javax.swing.JMenuItem jMenuRestBD;
    private javax.swing.JMenuItem jMenuVerDic;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
